### PR TITLE
Implement user display name override

### LINKED ISSUE #1745: Allow for user display name overrides
Currently we always show the username of a user everywhere:

https://github.com/DMOJ/online-judge/blob/c189db30f5e734f18d6a9b1287004851118af84c/judge/models/profile.py#L151-L154

We could add a new column in `Profile`, e.g. `username_display_override`, that when present overrides the return value of that function. The use case is pre-registered contests were teams have names which cannot be expressed as usernames, and which we currently butcher.

### PR DESCRIPTION
**Pull request by quantum5**
Fixes #1745.

### CODE REVIEW

**Comment by kiritofeng** [comment]
Doesn't override problem author, nor https://github.com/DMOJ/online-judge/blob/master/templates/ticket/message.html#L5

**Comment by quantum5** [comment]
@kiritofeng fixed tickets, not sure what you mean about author, since it appears to work on the problem page.

**Review by kiritofeng — APPROVED** [review]
LGTM; I guess the thing about problem authors might've been some caching nonsense.

**Review by Ninjaclasher — APPROVED** [review]
Code looks good, but do we want to support filtering by the override in the select2 widget and profile admin?

**Pull request merged**
