### PR TITLE
Test Cases Improvements

### PR DESCRIPTION
**Pull request by FherStk**
Dear DMOJ team,

I developed the following (in my opinion) improvements:
## Test cases (edit form):
- When entering on 'edit test cases', if no data has been entered through the site but the test-cases have been created manually into the file system, the file-system data will be loaded automatically to maintain the website/file-system consistency. This loading process is performed by parsing the YML file, useful when the problems are created using a script (for example, when migrating from other platforms into DMOJ).
- When selecting 'clean the zip file', all the test cases will be also removed to keep the consistency between the displayed data, the database and the YML file.
- A new dropdown option called 'Overwrite test cases from zip file' has been added (disabled by default). If enabled, the test-cases will be automatically loaded and created using all the zip file entries (using default data, zero points also). Useful to quickly load all the test-cases from a zip: 
image

## Problem (edit form and statement):
- A new option called 'Include test cases' has been added to the 'edit problem' form (disabled by default, no pre-tests will be shown):  
image  
When enabled, the current test-cases will be displayed after the problem statement (the content of the in/out files within the zip file will be used). This data is being stored into the database, in the problem_data model: 
image
Including the test-cases input and output manually in the problem statement is still possible, just non-enabling this new option, but this option is useful to avoid inconsistencies between the stored test files and the displayed data. 
- A new option has been included for attribution purposes, in order to give the authorship to external DMOJ users (like websites, books, etc):
image
This data will be displayed at the end of the problem statement, just before the license:
image

## General:
- Added new django settings to disable social and comments sections (false by default):
image

Social and comments enabled (by default):
image

Social and comments disabled:
image

### CODE REVIEW

**Comment by Xyene** [comment]
Thanks for the contribution! Could you please split up the "test case" / "problem" / "general" features in separate PRs, so that they may be reviewed and merged independently?

**Comment by FherStk** [comment]
> Thanks for the contribution! Could you please split up the "test case" / "problem" / "general" features in separate PRs, so that they may be reviewed and merged independently?

Sure! Which way would be the best for you: incremental PRs or independent PRs?

Thanks again and have a nice holidays 😊
Fher

**Comment by Xyene** [comment]
Independent PRs would be best. Some of these changes I think we could ~straightforwardly merge:

* Disabling comments
* Disabling social posts
* Authorship would close https://github.com/DMOJ/online-judge/issues/42 / https://github.com/DMOJ/online-judge/issues/144

For the others:

> * When entering on 'edit test cases', if no data has been entered through the site but the test-cases have been created manually into the file system, the file-system data will be loaded automatically to maintain the website/file-system consistency. 

I think this shouldn't live in the site UI. The YAML format we use allows embedding Python code that is evaluated to construct YAML nodes (this is useful for implementing problems with random test case orders, for instance), and such problems inherently can't be represented in the site UI.

It may make sense as an `import-simple-problem`-type management command though?

> * When selecting 'clean the zip file', all the test cases will be also removed to keep the consistency between the displayed data, the database and the YML file.
>
> * A new dropdown option called 'Overwrite test cases from zip file' has been added (disabled by default). If enabled, the test-cases will be automatically loaded and created using all the zip file entries (using default data, zero points also). Useful to quickly load all the test-cases from a zip ...

I like this idea, but maybe we could make the UI a little simpler: have a single checkbox be "Infer test cases from zip", and if checked it blows away any existing test cases and repopulates them from the zip. Bonus points if it keeps any assigned point/pretest/etc. values from a preceding upload for cases named the same.

**Comment by FherStk** [comment]
Hi,

Thanks again for your feedback, it's always a pleasure to collaborate with you.

About `I think this shouldn't live in the site UI. The YAML format we use allows embedding Python code that is evaluated to construct YAML nodes (this is useful for implementing problems with random test case orders, for instance), and such problems inherently can't be represented in the site UI.` maybe I can just display a warning (something like "A zip file has been found within the file system. If needed, you can populate the test cases from it". 

This approach will use the "populate test cases" implementation if the users requests it, simplifying the relying code.

Thanks again,
Fher

**Comment by FherStk** [comment]
Created the first independent PR: https://github.com/DMOJ/online-judge/pull/2303

**Comment by FherStk** [comment]
Hi there, 

I completed the independent PRs: 
- https://github.com/DMOJ/online-judge/pull/2303
- https://github.com/DMOJ/online-judge/pull/2304
- https://github.com/DMOJ/online-judge/pull/2305

I keep this PR closed, as it became outdated. 
Please, do not hesitate contacting me if you need further information or additional changes, it's a pleasure to collaborate with this project :)
 
Kind regards,
Fher

**Pull request closed without merging**
