### PR TITLE
Remove rate button for ongoing contests; #1592

### LINKED ISSUE #1592: Disable Rate button for ongoing contests...
...as #1591 renders this a noop.

### PR DESCRIPTION
**Pull request by Carson-Tang**
Fixes #1592.

### CODE REVIEW

**Review by kiritofeng — APPROVED** [review]
LGTM

**Review by Ninjaclasher — COMMENTED** [review]
Current change looks good, but I think you should also 404 [here](https://github.com/DMOJ/online-judge/blob/master/judge/admin/contest.py#L281).

**Comment by Carson-Tang** [comment]
> 
> 
> Current change looks good, but I think you should also 404 [here](https://github.com/DMOJ/online-judge/blob/master/judge/admin/contest.py#L281).

Added the changes suggested.

**Review by Ninjaclasher — APPROVED** [review]

**Review by Xyene — APPROVED** [review]
Thanks!

**Pull request merged**
