### PR TITLE
fix: security - window.opener property should not be available for third party sites.

### PR DESCRIPTION
**Pull request by subramanian0**

### CODE REVIEW

**Comment by quantum5** [comment]
This pull request contains unrelated changes.

**Comment by subramanian0** [comment]
@quantum5  : The other change is already approved in another PR (1736) but I guess its not yet merged to master. Should I delete the other changes in fork and submit a new PR with only this change?

**Comment by quantum5** [comment]
First of all, the other change has been merged. Also, you should properly rebase this change so that it just has the relevant commit.

**Comment by subramanian0** [comment]
@quantum5  : Thanks, merged DMOJ:master to forked:master. Now the diff only has relevant changes.

**Review by quantum5 — APPROVED** [review]

**Pull request merged**
