### PR TITLE
Clean up blog page css

### PR DESCRIPTION
**Pull request by int-y1**
Visible changes:
* Blog sidebar became slightly narrower.
* "RSS / Atom" is moved up 0.25em.

### CODE REVIEW

**Comment by Xyene** [comment]
Could you please attach some screenshots?

**Comment by int-y1** [comment]
> Could you please attach some screenshots?

Before:


After:

**Comment by Xyene** [comment]
Before, the contents of ongoing contests / comment stream / new problems had the same amount of left margin (roughly matching the amount of top margin), while now only the comment stream and new problems do.

**Comment by int-y1** [comment]
Reverted flexbox ratios. Now, the only visible change is "RSS / Atom".

**Review by Xyene — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
