### PR TITLE
Return message instead of 404 for muted users on edit profile page

### PR DESCRIPTION
**Pull request by Ninjaclasher**

### CODE REVIEW

**Comment by int-y1** [comment]
Is 400 or 403 more appropriate here? Otherwise, lgtm.

**Comment by int-y1** [comment]
Change `Bad request` to `Can't edit profile` to make it clear that the user is trying to edit profile.

**Comment by Ninjaclasher** [comment]
>  Is 400 or 403 more appropriate here?
Changed to `403`.
> Change Bad request to Can't edit profile to make it clear that the user is trying to edit profile.
Done.

**Review by kiritofeng — APPROVED** [review]
LGTM

**Review by Xyene — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
